trigger:
- main
pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: sonar_token
  value: $[variables.SONARTOKEN]
- name: snyk_token
  value: $[variables.SNYKTOKEN]

jobs:
- job: Sonar_SAST_Scan_Job
  container: maven:3.8.1-openjdk-17-slim
  steps:
  - script: |
      mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=azuredevopsdevsecopsoorgjou -Dsonar.projectKey=azuredevopsdevsecopsoorgjou -Dsonar.token=$(sonar_token)
    displayName: "Integrate SAST using Sonarcloud to populate code coverage" 

- job: Snyk_SCA_Scan_Job
  dependsOn: Sonar_SAST_Scan_Job
  steps:
  - script: |
      SNYK_TOKEN=$(snyk_token)
      export SNYK_TOKEN
      mvn snyk:test -fn 
    displayName: "Integrate SCA scan using Snyk in ADO DevSecOps Pipeline"

- job: ZAP_DAST_Scan_Job
  dependsOn: Snyk_SCA_Scan_Job
  steps:
  - script: |
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
        tar -xvf ZAP_2.14.0_Linux.tar.gz
        cd ZAP_2.14.0
        ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout /home/vsts/work/1/a/zap_report.html 
    displayName: "Integrate DAST scan using OWASP ZAP in ADO DevSecOps Pipeline"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: zap_report.html

